### ISSUE TITLE
Feature Request: Import multiple google docs as a single text

### ISSUE THREAD

**Issue by mkgold** [ManifoldScholar/manifold#1070]
[This has been significantly revised from Matt's initial post to reflect subsequent discussion. -ZD]

## Feature Description
This feature would allow text creators to combine multiple google docs into a single Manifold text. The ingestion process would be modified to support a new type of ingestion called "Google Docs Manifest" (working title, exact nomenclature TBD). During ingestion, the user would import a YML manifest that expressed the text structure. The structure of the manifest would look like this:
```
meta: 
  title: "A Collection of Google Docs"
  authors:
    - name: Jenny Wilkerson
    - name: Jimmy Wolkerson
toc:
  - title: Introduction
    url: http://docs.google.com/introduction
  - title: Section 1
    url: http://docs.google.com/section-1
    starting_section: true
    children:
      - title: Section 1.a
        url: http://docs.google.com/section-1-a
      - title: Section 1.b
        url: http://docs.google.com/section-1-b
  - title: Section 2
    url: http://docs.google.com/section-2
```

The ingestion strategy would generate a table of contents based on that structure. A text section (rather than a text) would be created from each Google doc referenced in the manifest. Meta data would be stored in the `meta` section of the yaml. We'd stick with dublin tags for metadata, or some similar spec wherever possible. Ideally, we'd keep it close to the meta attributes we look for in EPUBs for simplicity.

## *Why* is this feature important? *Who* does it help?
This would allow a group with many discrete but related google docs to create a single publication out of them. We believe this could be a common use case among groups of scholars or at academic centers.

## Design Notes
We probably need to improve the ingestion flow generally and give it a design pass. Ideally, we'd be able to provide documentation and help text about this format during ingestion.
