### ISSUE TITLE
Better control of TOC generation in the manifest

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#1857]
I have some issues with TOC generation.

I have an HTML file which uses h1 and h2 headers. When I ingest the text by uploading the HTML file only the auto-generated TOC contains both types of headers. The resulting text, however, is to long to be shown at once. I therefore split the file into 3 HTML files - each file for one of the h1 headers uns use the manifest.yml ingest procedure. Everything works well, except, the TOC now only includes the three h1 headers without the h2 headers. Hence, it seems the HTML files are no longer parsed for headers beyond those I assigned with labels in the manifest.yml. This is unfortunate insofar it is also not reasonable in my case to split the document further. Consider a 400 pages book with 3 levels of headings which you will then have to split up into, let's guess, 50 documents for the only reason to have them recognized in the TOC.

Is there a way to combine TOC generation via parsing the documents and declaring sections in the manifest holding its own files. I tried out to declare sections in the manifest by giving them the same label in the manifest than the section's title within the document, but this didn't work. I think if something comparable is no possible two logics conflict here, one being the reason for splitting up a document for not having endless websites, the other being the whish to control what appears in the TOC.

Suggestion from discussion on Slack using URL fragments:

https://manifold-community.slack.com/archives/C8LFMHM0X/p1549030734053200

```
toc:
  - label: Foo
    source_path: foo.html
    start_section: true
    children:
      - label: Bar Part 1
        source_path: bar.md#part-1
      - label: Bar Part 2
        source_path: bar.md#part-2
      - label: Bar Part 3
        source_path: bar.md#part-3
  - label: Baz
    source_path: baz.html
```
