### ISSUE TITLE
Improve manifest start_section implementation

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#2029]
Given a manifest TOC like this:
```
toc:
  - label: Google Doc Demo
    source_path: some/url
    children:
      - label: Hartigan HTML
        source_path: sharing-digitally.html#second
        start_section: true
        children:
          - label: 1. The Eve of War
            source_path: wow-ch01.md
```

The reader will always start from the first whole source path.  This means that even if `Hartigan HTML` was in the first position, the reader will fetch `Google Doc Demo` as the first section.  

Unclear off hand where this is failing, but I think it's in the spine generation.
