### ISSUE TITLE
Google Doc links to Manifold URL carry Google Site Referral

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2235]
If I include a link to a Manifold text within a Google Doc, the URL that comes into Manifold includes the following prefix `https://www.google.com/url?q=`, which forces the user to okay the redirect to the intended Manifold page.

An example of this in action can be seen [here](https://demo.manifoldapp.org/read/untitled-bfdd05e3-cb6f-4aae-b3f5-6680cfc65286/section/73b45027-50b0-490f-88a7-b40cdd00c891), with the link attached to the text reading “The paragraph continues here”.

**Comment by zdavis** [comment]
I see two issues here.

First: in Ingestion::Fetchers::GoogleDoc, we should strip out the google url proxy that Terence includes above.

Second: We need to provide a better way to link to items in a manifest. We might want to consider doing something like this:

```
toc:
  - label: Google Doc Test A
    source_path: https://docs.google.com/document/d/1LibU9ACTyHZ20Z9nzzReKiSwdt1i5yiNUovL8tO2nrE/edit?usp=sharing
     id: test-a
  - label: Google Doc Test B
    source_path: https://docs.google.com/document/d/1-pvK7dsOy-ebt5Ox_sUw-gsomSUtbFV4svXlMIvfoPo/edit?usp=sharing
     id: test-b
```

And then in the link in test b google doc, we'd link to `#test-a`. This way, the user doesn't have to deal in Manifold IDs, and Manifold can work out the links itself.
