### ISSUE TITLE
User stylesheets are unintentionally validated during reingestion

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2399]
On the Lapham's Quarterly instance, when a text is reingested user-created stylesheets aren't applying as expected. See this text: `https://laphamsquarterly.manifoldapp.org/read/stylesheet-test/section/b3bdbaf7-1e80-4aac-8373-3f9d4f9c1549`. When a change is made, the Drop Cap stylesheet no longer applies, though it will apply as expected if a user deletes and then recreates it. Of note, the stylesheet includes the line-height element:

```css
.drop-cap {
    line-height: 0.5em;
}

.undrop {
    font-weight: normal;
    position: relative;
}
```

A possible second issue with this text is the `head-2` stylesheet that is showing in the list. That CSS is empty and was not part of the original or subsequent ingests.
