### ISSUE TITLE
Add support for @media queries 

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold#2788]
Manifold presently strips media queries out of user-supplied CSS files:

For example, this block

```css
@media all and (max-width: 400px) {
  .row {
    flex-direction: column;
  }
}
```

become this

```css
.manifold-text-section .row {
    flex-direction: column;
}
```

If media queries were supported, however, publishers could leverage them to render content differently for desktop and mobile environments.

I'm at work now on a bilingual project that employs two-column lists for comparative purposes. In the desktop environment, having those comparisons appear next to the other is ideal. Not so in mobile, where the experience is compromised by reduced screen size. Instead, at that scale, it would be a better reading experience to have those blocks of content stacked on top of one another.
