### ISSUE TITLE
start_section with fragment uris in source_path does not work

### ISSUE THREAD

**Issue by Cutuchiqueno** [ManifoldScholar/manifold#3010]
It appears that `start_section: true` in the _manifest.yml_ in order to mark a specific section as the one that opens first after clicking the publication/text link only works for sections, relating to a single file but not sections with a fragment URL?

Consider the following example:

```yaml
toc:
  - label: "Book Cover"
    source_path: "cover.html"
  - label: "Title Page"
    source_path: "second_cover.html"
  - label: "Editorial"
    source_path: "editorial.html"
  - label: "Crisis? What Crisis? Die abendländische Rationalität im Entwicklerbad der Coronakrise"
    source_path: "eoh_02_mein_crisis.html#index.xml-body.1_div.1"
    start_section: true
  - label: "Literatur"
    source_path: "eoh_02_mein_crisis.html#index.xml-body.1_div.2"
```

Despite the `start_section` key for _Crisis? What Crisis? ..._, the publication always starts with `cover.html` , regardless if I come to it from a _Start reading_ button on the landing page or from a _Texts block_ on the landing page in which it is enlisted.

If it is only possible to do this with sections that corresponds to entire files but not with fragments, I think Manifold should support both, b/c it supports both URLs in the `source_path` key.
